---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress
  labels:
    app: haproxy-ingress
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      nodePort: 30062
    - port: 443
      name: https
      nodePort: 30063
    - port: 1936
      name: stats
      nodePort: 30091
    - port: 1937
      name: prometheus
      nodePort: 30092
  clusterIP: 10.144.0.4
  selector:
    k8s-app: haproxy-ingress-lb
    app: haproxy-ingress-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy-ingress
  labels:
    service-monitor: haproxy-ingress
spec:
  selector:
    matchLabels:
      app: haproxy-ingress
  endpoints:
  - port: prometheus
