apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: /etc/kubernetes/ca.pem
    server: https://KUBEAPISERVER
users:
- name: ingress-controller
  user:
    client-certificate: /etc/kubernetes/ingress-controller.pem
    client-key: /etc/kubernetes/ingress-controller.key
contexts:
- context:
    cluster: local
    user: ingress-controller
  name: ingress-controller-context
current-context: ingress-controller-context

