apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: haproxy-metrics-prom
  labels:
    app: haproxy-metrics-prom
    prometheus: haproxy-metrics-prom
spec:
  replicas: 1
  baseImage: prom/prometheus
  version: v2.2.1
  serviceAccountName: prometheus
# An empty serviceMonitorSelector means we use a custom configuration
  serviceMonitorSelector:
  resources:
    requests:
      memory: 300Mi
  retention: 7d
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-metrics-prom
  labels:
    app: haproxy-metrics-prom
    prometheus: haproxy-metrics-prom
spec:
  type: NodePort
  clusterIP: 10.144.0.5
  ports:
  - name: web
    nodePort: 30999
    port: 9090
    targetPort: web
  selector:
    prometheus: haproxy-metrics-prom
